import { PackageItem, ServiceItem, PaymentMilestone, Invoice, CatalogService, Client } from './types';

export const SERVICE_CATALOG: CatalogService[] = [
  { id: 'svc-uiux',        name: 'UI/UX Design',             category: 'Design',      price: 6000,  taxPercent: 18, description: 'Complete website interface and user experience design' },
  { id: 'svc-webdesign',   name: 'Website Design',           category: 'Design',      price: 10000, taxPercent: 18, description: 'Full multi-page website visual design' },
  { id: 'svc-webdev',      name: 'Website Development',      category: 'Development', price: 15000, taxPercent: 18, description: 'Responsive front-end build and deployment' },
  { id: 'svc-landing',     name: 'Landing Page Design',      category: 'Design',      price: 5000,  taxPercent: 18, description: 'High-conversion single-page design' },
  { id: 'svc-appui',       name: 'Mobile App UI Design',     category: 'Design',      price: 8000,  taxPercent: 18, description: 'iOS and Android interface screens' },
  { id: 'svc-logo',        name: 'Logo Design',              category: 'Branding',    price: 3000,  taxPercent: 18, description: 'Primary logo with variations and source files' },
  { id: 'svc-branding',    name: 'Branding Package',         category: 'Branding',    price: 12000, taxPercent: 18, description: 'Logo, palette, typography and brand guidelines' },
  { id: 'svc-graphic',     name: 'Graphic Design',           category: 'Design',      price: 2500,  taxPercent: 18, description: 'Custom graphics and marketing collateral' },
  { id: 'svc-smm',         name: 'Social Media Management',  category: 'Marketing',   price: 8000,  taxPercent: 18, description: 'Monthly content planning and scheduling' },
  { id: 'svc-smpost',      name: 'Social Media Post Design', category: 'Design',      price: 1500,  taxPercent: 18, description: 'Single campaign post creative' },
  { id: 'svc-seo',         name: 'SEO Optimization',         category: 'Marketing',   price: 5000,  taxPercent: 18, description: 'On-page SEO, metadata and performance tuning' },
  { id: 'svc-content',     name: 'Content Writing',          category: 'Content',     price: 2000,  taxPercent: 18, description: 'Website copy and marketing content' },
  { id: 'svc-video',       name: 'Video Editing',            category: 'Media',       price: 4000,  taxPercent: 18, description: 'Edit, colour grade and export' },
  { id: 'svc-motion',      name: 'Motion Graphics',          category: 'Media',       price: 6000,  taxPercent: 18, description: 'Animated graphics and transitions' },
  { id: 'svc-3d',          name: '3D Design',                category: 'Design',      price: 8000,  taxPercent: 18, description: '3D modelling, texturing and rendering' },
  { id: 'svc-digital',     name: 'Digital Marketing',        category: 'Marketing',   price: 10000, taxPercent: 18, description: 'Paid campaigns and funnel management' },
  { id: 'svc-maintenance', name: 'Website Maintenance',      category: 'Support',     price: 3000,  taxPercent: 18, description: 'Monthly updates, backups and monitoring' },
  { id: 'svc-consulting',  name: 'Consulting',               category: 'Strategy',    price: 3000,  taxPercent: 18, description: 'Strategy and technical advisory session' },
  { id: 'svc-custom',      name: 'Custom Service',           category: 'Custom',      price: 0,     taxPercent: 18, description: 'Custom tailored client service deliverable' },
  { id: 'svc-other',       name: 'Other',                    category: 'Custom',      price: 0,     taxPercent: 18, description: 'Miscellaneous product or service item' },
];

export const DEFAULT_PACKAGES: PackageItem[] = [
  { id: 'pkg-1', name: 'Starter Website', price: 8000 },
  { id: 'pkg-2', name: 'Business Website', price: 20000 },
  { id: 'pkg-3', name: 'Premium Website', price: 35000 },
  { id: 'pkg-4', name: 'E-Commerce Website', price: 50000 },
  { id: 'pkg-5', name: 'Enterprise Website', price: 0, isCustomPrice: true },
];

export const INITIAL_SERVICES: ServiceItem[] = SERVICE_CATALOG.map((svc) => ({
  id: svc.id,
  name: svc.name,
  price: svc.price,
  quantity: 1,
  selected: false,
}));

export const INITIAL_ADDONS: ServiceItem[] = [
  'Premium Animations',
  'Interactive UI',
  'Custom Illustrations',
  'AI Chatbot',
  'Google Analytics',
  'Google Search Console',
  'Maintenance',
  'Content Upload',
  'Product Upload',
  'Image Optimization',
].map((name, i) => ({
  id: `addon-${i}`,
  name,
  price: 3000,
  quantity: 1,
  selected: false,
}));

export const DEFAULT_PAYMENT_SCHEDULE: PaymentMilestone[] = [
  { id: 'pm-1', percentage: 50, description: 'Advance' },
  { id: 'pm-2', percentage: 30, description: 'After Design' },
  { id: 'pm-3', percentage: 20, description: 'Before Delivery' },
];

export const DEFAULT_TERMS = [
  'All prices are subject to GST as applicable (18%).',
  'Domain & Hosting renewals are annual and billed separately.',
  'The advance payment is non-refundable upon project kickoff.',
  'Content, branding assets and media must be provided by the client.',
  'Post-launch support is limited to the agreed maintenance terms.',
  'Late payments may incur a 1.5% monthly service penalty.',
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'Alex Rivera',
    companyName: 'ABC Technologies',
    email: 'alex@abctech.io',
    phone: '+91 98765 43210',
    address: 'Level 4, Cyber City, Indiranagar, Bangalore 560038',
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'client-2',
    name: 'Maya Lin',
    companyName: 'XYZ Studio',
    email: 'maya@xyzstudio.design',
    phone: '+91 98220 11234',
    address: '1202 Signature Tower, BKC, Bandra Mumbai 400051',
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'client-3',
    name: 'Devon Vance',
    companyName: 'Apex Ventures',
    email: 'devon@apexventures.co',
    phone: '+91 91234 56789',
    address: 'Floor 18, One Horizon Center, Golf Course Rd, Gurugram 122002',
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
];

const today = new Date();
const formattedToday = today.toISOString().split('T')[0];
const dueTwoWeeks = new Date();
dueTwoWeeks.setDate(today.getDate() + 14);
const formattedDue = dueTwoWeeks.toISOString().split('T')[0];

export const createEmptyInvoice = (invoiceNumber: string): Invoice => ({
  id: crypto.randomUUID(),
  invoiceNumber,
  invoiceDate: formattedToday,
  dueDate: formattedDue,
  status: 'pending',
  currency: 'INR',
  clientId: 'client-1',
  company: {
    name: 'Noir Labs',
    phone: '+91 9167868179',
    email: 'juzer09jawadwala@gmail.com',
    website: 'www.noirlabs.com',
    gstNumber: '27AABCU9603R1ZM',
    address: 'Anjeerwadi, Thakkar Estate, Mazgaon, Mumbai 400010',
  },
  client: {
    name: 'Alex Rivera',
    companyName: 'ABC Technologies',
    email: 'alex@abctech.io',
    phone: '+91 98765 43210',
    address: 'Level 4, Cyber City, Indiranagar, Bangalore 560038',
    projectName: 'Brand & Platform Experience',
  },
  items: [
    {
      id: 'item-1',
      serviceId: 'svc-uiux',
      name: 'UI/UX Design',
      description: 'Complete website interface and user experience design',
      quantity: 1,
      rate: 6000,
      discountPercent: 0,
      taxPercent: 18,
    },
    {
      id: 'item-2',
      serviceId: 'svc-webdev',
      name: 'Website Development',
      description: 'Responsive front-end build and deployment',
      quantity: 1,
      rate: 15000,
      discountPercent: 0,
      taxPercent: 18,
    },
    {
      id: 'item-3',
      serviceId: 'svc-logo',
      name: 'Logo Design',
      description: 'Primary logo with variations and source files',
      quantity: 1,
      rate: 3000,
      discountPercent: 0,
      taxPercent: 18,
    },
  ],
  selectedPackage: null,
  customPackagePrice: 0,
  services: INITIAL_SERVICES,
  addons: INITIAL_ADDONS,
  discount: 0,
  gstPercent: 18,
  advancePaid: 0,
  paymentSchedule: DEFAULT_PAYMENT_SCHEDULE,
  notes: 'Thank you for partnering with Noir Labs. We are excited to engineer a first-class digital experience.',
  terms: DEFAULT_TERMS,
  createdAt: Date.now(),
  updatedAt: Date.now(),
});

export const DEMO_INVOICES_SEED: Invoice[] = [
  {
    id: 'demo-inv-1001',
    invoiceNumber: 'INV-1001',
    invoiceDate: '2026-08-16',
    dueDate: '2026-08-30',
    status: 'pending',
    currency: 'INR',
    clientId: 'client-1',
    company: {
      name: 'Noir Labs',
      phone: '+91 9167868179',
      email: 'juzer09jawadwala@gmail.com',
      website: 'www.noirlabs.com',
      gstNumber: '27AABCU9603R1ZM',
      address: 'Anjeerwadi, Thakkar Estate, Mazgaon, Mumbai 400010',
    },
    client: {
      name: 'Alex Rivera',
      companyName: 'ABC Technologies',
      email: 'alex@abctech.io',
      phone: '+91 98765 43210',
      address: 'Level 4, Cyber City, Indiranagar, Bangalore 560038',
      projectName: 'Brand & Platform Experience',
    },
    items: [
      {
        id: 'item-1',
        serviceId: 'svc-uiux',
        name: 'UI/UX Design',
        description: 'Complete website interface and user experience design',
        quantity: 1,
        rate: 6000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-2',
        serviceId: 'svc-webdev',
        name: 'Website Development',
        description: 'Responsive front-end build and deployment',
        quantity: 1,
        rate: 15000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-3',
        serviceId: 'svc-logo',
        name: 'Logo Design',
        description: 'Primary logo with variations and source files',
        quantity: 1,
        rate: 3000,
        discountPercent: 0,
        taxPercent: 18,
      },
    ],
    selectedPackage: null,
    customPackagePrice: 0,
    services: INITIAL_SERVICES,
    addons: INITIAL_ADDONS,
    discount: 0,
    gstPercent: 18,
    advancePaid: 0,
    paymentSchedule: DEFAULT_PAYMENT_SCHEDULE,
    notes: 'Thank you for your business. We look forward to delivering a premium digital experience.',
    terms: DEFAULT_TERMS,
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'demo-inv-1000',
    invoiceNumber: 'INV-1000',
    invoiceDate: '2026-08-12',
    dueDate: '2026-08-26',
    status: 'paid',
    currency: 'INR',
    clientId: 'client-2',
    company: {
      name: 'Noir Labs',
      phone: '+91 9167868179',
      email: 'juzer09jawadwala@gmail.com',
      website: 'www.noirlabs.com',
      gstNumber: '27AABCU9603R1ZM',
      address: 'Anjeerwadi, Thakkar Estate, Mazgaon, Mumbai 400010',
    },
    client: {
      name: 'Maya Lin',
      companyName: 'XYZ Studio',
      email: 'maya@xyzstudio.design',
      phone: '+91 98220 11234',
      address: '1202 Signature Tower, BKC, Bandra Mumbai 400051',
      projectName: 'Website Design & Rebrand',
    },
    items: [
      {
        id: 'item-201',
        serviceId: 'svc-webdesign',
        name: 'Website Design',
        description: 'Full multi-page website visual design',
        quantity: 1,
        rate: 10000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-202',
        serviceId: 'svc-landing',
        name: 'Landing Page Design',
        description: 'High-conversion single-page design',
        quantity: 1,
        rate: 5000,
        discountPercent: 0,
        taxPercent: 0,
      },
    ],
    selectedPackage: null,
    customPackagePrice: 0,
    services: INITIAL_SERVICES,
    addons: INITIAL_ADDONS,
    discount: 0,
    gstPercent: 18,
    advancePaid: 16800,
    paymentSchedule: DEFAULT_PAYMENT_SCHEDULE,
    notes: 'Payment received with thanks. Fully settled.',
    terms: DEFAULT_TERMS,
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'demo-inv-0999',
    invoiceNumber: 'INV-0999',
    invoiceDate: '2026-08-05',
    dueDate: '2026-08-19',
    status: 'paid',
    currency: 'INR',
    clientId: 'client-3',
    company: {
      name: 'Noir Labs',
      phone: '+91 9167868179',
      email: 'juzer09jawadwala@gmail.com',
      website: 'www.noirlabs.com',
      gstNumber: '27AABCU9603R1ZM',
      address: 'Anjeerwadi, Thakkar Estate, Mazgaon, Mumbai 400010',
    },
    client: {
      name: 'Devon Vance',
      companyName: 'Apex Ventures',
      email: 'devon@apexventures.co',
      phone: '+91 91234 56789',
      address: 'Floor 18, One Horizon Center, Golf Course Rd, Gurugram 122002',
      projectName: 'Full Digital Transformation',
    },
    items: [
      {
        id: 'item-301',
        serviceId: 'svc-branding',
        name: 'Branding Package',
        description: 'Logo, palette, typography and brand guidelines',
        quantity: 1,
        rate: 12000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-302',
        serviceId: 'svc-webdev',
        name: 'Website Development',
        description: 'Responsive front-end build and deployment',
        quantity: 2,
        rate: 15000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-303',
        serviceId: 'svc-digital',
        name: 'Digital Marketing',
        description: 'Paid campaigns and funnel management',
        quantity: 1,
        rate: 10000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-304',
        serviceId: 'svc-3d',
        name: '3D Design',
        description: '3D product modeling and visual assets',
        quantity: 2,
        rate: 8000,
        discountPercent: 0,
        taxPercent: 18,
      },
      {
        id: 'item-305',
        serviceId: 'svc-seo',
        name: 'SEO Optimization',
        description: 'On-page SEO, metadata and performance tuning',
        quantity: 1,
        rate: 5000,
        discountPercent: 0,
        taxPercent: 18,
      },
    ],
    selectedPackage: null,
    customPackagePrice: 0,
    services: INITIAL_SERVICES,
    addons: INITIAL_ADDONS,
    discount: 0,
    gstPercent: 18,
    advancePaid: 86140,
    paymentSchedule: DEFAULT_PAYMENT_SCHEDULE,
    notes: 'Enterprise contract milestone 1 completed and signed off.',
    terms: DEFAULT_TERMS,
    createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
];
